### PR TITLE
fix(ci): variants block does not carry tailwind prefix

### LINKED ISSUE #1610: [Bug]: missing tailwind prefix in src/components/ui/field/index.ts
### Reproduction

configure components.json with tailwind.prefix as"tw" and run pnpm dlx shadcn-vue@latest add field

### Describe the bug

components.json
```json
{
  "$schema": "https://shadcn-vue.com/schema.json",
  "style": "new-york",
  "typescript": true,
  "tailwind": {
    "config": "",
    "css": "src/style/tailwind.css",
    "baseColor": "neutral",
    "cssVariables": true,
    "prefix": "tw"
  },
  "aliases": {
    "components": "@/components",
    "composables": "@/composables",
    "utils": "@/lib/utils",
    "ui": "@/components/ui",
    "lib": "@/lib"
  },
  "iconLibrary": "lucide"
}
```
then run
```bash
pnpm dlx shadcn-vue@latest add field
```
and check: src/components/ui/field/index.ts
```ts
import type { VariantProps } from "class-variance-authority"
import { cva } from "class-variance-authority"

export const fieldVariants = cva(
  'tw:group/field tw:flex tw:w-full tw:gap-3 tw:data-[invalid=true]:text-destructive',
  {
    variants: {
      orientation: {
        vertical: ["flex-col [&>*]:w-full [&>.sr-only]:w-auto"],
        horizontal: [
          "flex-row items-center",
          "[&>[data-slot=field-label]]:flex-auto",
          "has-[>[data-slot=field-content]]:items-start has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
        ],
        responsive: [
          "flex-col [&>*]:w-full [&>.sr-only]:w-auto @md/field-group:flex-row @md/field-group:items-center @md/field-group:[&>*]:w-auto",
          "@md/field-group:[&>[data-slot=field-label]]:flex-auto",
          "@md/field-group:has-[>[data-slot=field-content]]:items-start @md/field-group:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
        ],
      },
    },
    defaultVariants: {
      orientation: "vertical",
    },
  },
)

export type FieldVariants = VariantProps<typeof fieldVariants>

export { default as Field } from "./Field.vue"
export { default as FieldContent } from "./FieldContent.vue"
export { default as FieldDescription } from "./FieldDescription.vue"
export { default as FieldError } from "./FieldError.vue"
export { default as FieldGroup } from "./FieldGroup.vue"
export { default as FieldLabel } from "./FieldLabel.vue"
export { default as FieldLegend } from "./FieldLegend.vue"
export { default as FieldSeparator } from "./FieldSeparator.vue"
export { default as FieldSet } from "./FieldSet.vue"
export { default as FieldTitle } from "./FieldTitle.vue"
```

All the class names inside the variants block are missing the ```tw:``` prefix.

### System Info

```bash
System:
    OS: macOS 26.1
    CPU: (14) arm64 Apple M4 Pro
    Memory: 2.63 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.19.0 - /usr/local/bin/node
    npm: 10.9.3 - /usr/local/bin/npm
    pnpm: 10.20.0 - /Users/adajoy/Library/pnpm/pnpm
    bun: 1.1.45 - /Users/adajoy/.bun/bin/bun
  Browsers:
    Chrome: 142.0.7444.176
    Safari: 26.1
  npmPackages:
    @vueuse/core: ^13.9.0 => 13.9.0 
    reka-ui: ^2.5.1 => 2.5.1 
    vue: ^3.5.13 => 3.5.21
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

### PR DESCRIPTION
**Pull request by jevin98**
### 🔗 Linked issue
close #1610

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/cli/src/utils/transformers/transform-tw-prefix.ts [hunk 1]
```diff
@@ -141,8 +141,15 @@ export async function transformTwPrefix(opts: TransformOpts): Promise<CodemodPlu
                   const allProperties = astHelpers.findAll(variantsProperty.value, { type: 'Property' })
                   allProperties.forEach((prop: any) => {
                     if (prop.value?.type === 'Literal' && typeof prop.value.value === 'string') {
-                      prop.value.value = applyPrefix(prop.value.value, config.tailwind.prefix, tailwindVersion)
-                      transformCount++
+                      prop.value.value = addPrefix(prop.value.value)
+                    }
+                    // Handle ArrayExpression values (e.g., vertical: ["flex-col", "w-full"])
+                    else if (prop.value?.type === 'ArrayExpression') {
```
Comment (jevin98) [inline packages/cli/src/utils/transformers/transform-tw-prefix.ts]: add prefixes to `variants` is handled here.

**Review by sadeghbarati — APPROVED** [review]
```ts
export const fieldVariants = cva('tw:group/field tw:flex tw:w-full tw:gap-3 tw:data-[invalid=true]:text-destructive', {
  variants: {
    orientation: {
      vertical: ['tw:flex-col tw:[&>*]:w-full tw:[&>.sr-only]:w-auto'],
      horizontal: [
        'tw:flex-row tw:items-center',
        'tw:[&>[data-slot=field-label]]:flex-auto',
        'tw:has-[>[data-slot=field-content]]:items-start tw:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px',
      ],
      responsive: [
        'tw:flex-col tw:[&>*]:w-full tw:[&>.sr-only]:w-auto tw:@md/field-group:flex-row tw:@md/field-group:items-center tw:@md/field-group:[&>*]:w-auto',
        'tw:@md/field-group:[&>[data-slot=field-label]]:flex-auto',
        'tw:@md/field-group:has-[>[data-slot=field-content]]:items-start tw:@md/field-group:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px',
      ],
    },
  },
  defaultVariants: {
    orientation: 'vertical',
  },
})
```
