### PR TITLE
fix(cli): preserve intermediate directories when resolving nested file paths

### LINKED ISSUE #1605: [Bug]: Components with additional path levels installing to wrong directory in 2.4.0
### Reproduction

1. clone repo: https://github.com/cwandev/ai-chatbot
2. run: npx shadcn-vue@latest add https://registry.ai-elements-vue.com/artifact.json

### Describe the bug

When installing components from a custom registry that have additional path levels (e.g., `components/ai-elements/artifact/...`), the installation path is incorrect in shadcn-vue 2.4.0.

**Expected behavior:**
- Using shadcn-vue 2.3.3: Components install to `components/ai-elements/artifact/...` ✅

**Actual behavior:**
- Using shadcn-vue 2.4.0: Components install to `components/artifact/...` (missing the `ai-elements` intermediate directory) ❌

**Example:**
- Registry file path: `components/ai-elements/artifact/Artifact.vue`
- Expected: `components/ai-elements/artifact/Artifact.vue`
- Actual: `components/artifact/Artifact.vue`

This affects custom registries with `registry:component` types that have additional path levels beyond the base components directory.

### System Info

```bash
- shadcn-vue version: 2.4.0
- Node version: 22
- Package manager: pnpm
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

### PR DESCRIPTION
**Pull request by sadeghbarati**
### 🔗 Linked issue

resolve #1605

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Fixes component installation paths for custom registries with additional path levels. Previously, only the last segment of the common root was preserved, causing intermediate directories to be lost.

Example:
- Before: components/ai-elements/artifact/Artifact.vue → artifact/Artifact.vue
- After: components/ai-elements/artifact/Artifact.vue → ai-elements/artifact/Artifact.vue

The function now uses the component alias from config to correctly resolve paths for any custom registry structure, not just the default "components" directory.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/cli/src/utils/updaters/update-files.ts [hunk 1]
```diff
@@ -419,11 +419,28 @@ export function findCommonRoot(paths: string[], needle: string): string {
...
 ): string {
   // Normalize paths by removing leading/trailing slashes
   const normalizedFilePath = filePath.replace(/^\/|\/$/g, '')
   const normalizedCommonRoot = commonRoot.replace(/^\/|\/$/g, '')
 
+  // Get component alias without @ prefix and normalize
+  const componentAlias = config.aliases.components.replace(/^@\//, '').replace(/^\/|\/$/g, '')
+
+  // Check if the common root contains the component alias
+  if (normalizedCommonRoot.includes(componentAlias)) {
```
Comment (jevin98) [inline packages/cli/src/utils/updaters/update-files.ts]: If the user modifies `aliases.components = @/custom-component`, the if statement will not be executed here.
